/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-cc11xx
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_CC11XX_API_H
#define INCLUDED_CC11XX_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_cc11xx_EXPORTS
#define CC11XX_API __GR_ATTR_EXPORT
#else
#define CC11XX_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_CC11XX_API_H */
